// <auto-generated />
namespace Haxgo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class SiteDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SiteDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201312101140282_SiteDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
